import { runBacktest } from '../analysis/backtester.js';
import { POPULAR_PAIRS } from '../api/cryptoApi.js';

export class BacktestModal {
  constructor(container) {
    this.container = container;
    this.render();
    this.bindEvents();
  }

  render() {
    const symbolOptions = POPULAR_PAIRS.map(p => `<option value="${p.symbol}">${p.name}</option>`).join('');

    this.container.insertAdjacentHTML('beforeend', `
      <div id="backtest-modal" class="modal-overlay hidden">
        <div class="modal-card" style="max-width: 600px; padding: 24px;">
          <div class="modal-header" style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid var(--border-color); padding-bottom: 15px; margin-bottom: 20px;">
            <h2><i data-lucide="history"></i> AI Strategy Backtester</h2>
            <button id="close-backtest-modal" class="close-btn"><i data-lucide="x"></i></button>
          </div>
          <div class="modal-body">
            <p style="color: var(--text-secondary); margin-bottom: 20px; font-size: 14px;">
              Run a historical simulation on the last 1000 candles to see how the AI strategy would have performed.
            </p>

            <div style="display: flex; gap: 15px; margin-bottom: 20px;">
              <div style="flex: 1;">
                <label style="font-size: 12px; color: var(--text-muted); margin-bottom: 5px; display: block;">Symbol</label>
                <select id="backtest-symbol" class="blazity-input" style="width: 100%;">
                  ${symbolOptions}
                </select>
              </div>
              <div style="flex: 1;">
                <label style="font-size: 12px; color: var(--text-muted); margin-bottom: 5px; display: block;">Timeframe</label>
                <select id="backtest-timeframe" class="blazity-input" style="width: 100%;">
                  <option value="15m">15m (Scalp)</option>
                  <option value="1H" selected>1H (Day Trade)</option>
                  <option value="4H">4H (Swing)</option>
                </select>
              </div>
            </div>

            <button id="run-backtest-submit" class="blazity-btn-primary" style="width: 100%; justify-content: center;">
              Run Simulation
            </button>

            <div id="backtest-loading" class="hidden" style="text-align: center; margin-top: 20px;">
              <div class="spinner"></div>
              <p style="margin-top: 10px; font-size: 13px; color: var(--text-secondary);">Simulating history (this may take a few seconds)...</p>
            </div>

            <div id="backtest-results" class="hidden" style="margin-top: 30px;">
              <h3 style="margin-bottom: 15px; border-bottom: 1px solid var(--border-color); padding-bottom: 8px;">Results Report</h3>
              
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div title="The total number of buy/sell signals generated by the AI over the last 1000 candles." style="background: var(--bg-card); padding: 15px; border-radius: 8px; border: 1px solid var(--border-color); cursor: help;">
                  <div style="font-size: 12px; color: var(--text-muted);">Total Trades</div>
                  <div id="bt-total-trades" style="font-size: 20px; font-weight: bold; margin-top: 5px;">0</div>
                </div>
                <div title="The percentage of trades that successfully hit their Take Profit target before hitting the Stop Loss." style="background: var(--bg-card); padding: 15px; border-radius: 8px; border: 1px solid var(--border-color); cursor: help;">
                  <div style="font-size: 12px; color: var(--text-muted);">Win Rate</div>
                  <div id="bt-win-rate" style="font-size: 20px; font-weight: bold; margin-top: 5px; color: var(--support-green);">0%</div>
                </div>
                <div title="The total compounded percentage gained or lost if you took every trade the AI suggested." style="background: var(--bg-card); padding: 15px; border-radius: 8px; border: 1px solid var(--border-color); cursor: help;">
                  <div style="font-size: 12px; color: var(--text-muted);">Total Profit/Loss</div>
                  <div id="bt-pnl" style="font-size: 20px; font-weight: bold; margin-top: 5px;">0%</div>
                </div>
                <div title="The largest single drop in portfolio value from peak to trough during the backtest." style="background: var(--bg-card); padding: 15px; border-radius: 8px; border: 1px solid var(--border-color); cursor: help;">
                  <div style="font-size: 12px; color: var(--text-muted);">Max Drawdown</div>
                  <div id="bt-drawdown" style="font-size: 20px; font-weight: bold; margin-top: 5px; color: var(--resistance-red);">0%</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    `);
  }

  bindEvents() {
    this.modal = document.getElementById('backtest-modal');
    
    document.getElementById('close-backtest-modal').addEventListener('click', () => {
      this.close();
    });

    document.getElementById('run-backtest-submit').addEventListener('click', async () => {
      const symbol = document.getElementById('backtest-symbol').value;
      const tf = document.getElementById('backtest-timeframe').value;
      
      document.getElementById('run-backtest-submit').classList.add('hidden');
      document.getElementById('backtest-results').classList.add('hidden');
      document.getElementById('backtest-loading').classList.remove('hidden');

      try {
        const report = await runBacktest(symbol, tf);
        
        document.getElementById('bt-total-trades').innerText = report.totalTrades;
        document.getElementById('bt-win-rate').innerText = report.winRate.toFixed(2) + '%';
        
        const pnlEl = document.getElementById('bt-pnl');
        pnlEl.innerText = (report.totalProfitPercent > 0 ? '+' : '') + report.totalProfitPercent.toFixed(2) + '%';
        pnlEl.style.color = report.totalProfitPercent >= 0 ? 'var(--support-green)' : 'var(--resistance-red)';
        
        document.getElementById('bt-drawdown').innerText = '-' + report.maxDrawdown.toFixed(2) + '%';
        
        document.getElementById('backtest-results').classList.remove('hidden');
      } catch (err) {
        alert('Backtest error: ' + err.message);
      } finally {
        document.getElementById('backtest-loading').classList.add('hidden');
        document.getElementById('run-backtest-submit').classList.remove('hidden');
      }
    });
  }

  open() {
    this.modal.classList.remove('hidden');
    if (window.lucide) {
      window.lucide.createIcons();
    }
  }

  close() {
    this.modal.classList.add('hidden');
  }
}
